### ISSUE TITLE
Error thrown without any images

### ISSUE THREAD

**Issue by medienbaecker** [johannschopplich/kirby-seo-audit#2]
### Environment

Kirby 4.1.2
SEO Audit 1.4.1

### Describe the bug

SEO Audit throws an error when the page it checks doesn't have any images. In the console it looks like the check for alt attributes doesn't have a fallback.

### Logs

```shell-script
index.js?1710345082:74 TypeError: Cannot read properties of undefined (reading 'imageswithoutaltattribute')
```

**Comment by johannschopplich** [comment]
Thanks for reporting! 💯 

You're right, there was an issue with the alt attribute assessment. Fix has been pushed, tests have been updated. Also, there's now a new translation for when the page doesn't contain any images.

Release v1.4.2 is ready for you on your order page. 🙂
