### ISSUE TITLE
Draft page gives error 404

### ISSUE THREAD

**Issue by wdebusschere** [johannschopplich/kirby-seo-audit#4]
### Environment

All latest

### Reproduction

Do a seo audit of a draft page

### Describe the bug

It should add the token when a page is draft, cf kirby cms logic for previewing draft pages

**Comment by johannschopplich** [comment]
Thanks for the report! Can you provide more information on your setup, share blueprints, SEO Audit version, etc.? The latest version is [v1.5.0](https://kirbyseo.com/changelog). Have you installed it?

In fact, SEO Audit supports draft pages. The section fetches the `previewUrl` of a given page, which includes the `token` required for draft pages.

**Comment by johannschopplich** [comment]
Interesting. Do you have page models, middlewares or controllers that prevent this page URL from being accessed? 

Can you provide a minimum reproducible example for me, please? Seems like there's a configuration in your specific Kirby configuration that blocks Kirby's default preview URL from being callable.

**Comment by wdebusschere** [comment]
@johannschopplich Yes it's caused by some custom logic i have, has nothing to do with the plugin. Thanks
